### ISSUE TITLE
Librarian - maintain collection

### ISSUE THREAD

**Issue by AdamHerbst** [AdamHerbst/LibrarySystem#11]
As a librarian I want to be able to update and remove books in the database so that I can maintain the book collection.

Tasks: This functionality was implemented in the command line but we will be adding it to the GUI in EI #3.

**Comment by mauleenn** [comment]
Adam -- we should close this issue. Edit the title to say **(Database)** Librarian - maintain collection and in the comment edit it to say 

As a librarian I want to be able to update and remove books in the database so that I can maintain the book collection.

**Tasks: This functionality was implemented in the command line but we will be adding it to the GUI in EI #3**.

We will implement this in EI #1

**Comment by mauleenn** [comment]
This issue is closed. This functionality was implemented in the DB. We will implement it in the database during the third sprint.
